apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ktgy8gtmk-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ktgy8gtmk-java-quarkus-gitops